---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3321120119-AuALIWTPYzBdmdMlyMgH2t2p77u2fqx3lNFqGAF
:access_token_secret: xbb3fRyxpAOu9Oo6kkgs8RIINtyyDQGQDV88I4ZeaR2fH
